output_dir: ~/experiments/

dataset:
  class: KINSHIP
  path: ~/datasets/knowledge_graphs/

task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 512
    hidden_dims: [512, 512, 512, 512, 512, 512]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    degree: 150
    # activation: sigmoid
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 64

train:
  num_epoch: 20

metric: hits@1