output_dir: ~/experiments/

dataset:
  class: WN18RR
  path: ~/datasets/knowledge_graphs/

task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: rotate
    aggregate_func: pna
    short_cut: no
    layer_norm: yes
    dependent: yes
    degree: 150
    activation: relu
  criterion: bce
  num_negative: 16
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no

optimizer:
  class: AdamW
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 20

metric: hits@1